spring:
 datasource:
    url: jdbc:postgresql://localhost:5432/Brettspiel
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
 jackson:    serialization:      WRITE_DATES_AS_TIMESTAMPS : false      
 jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    